version: "3"

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    networks:
      - velocity

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "5778:5778/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268:14268"
      - "16686:16686"
    networks:
      - velocity

networks:
  velocity:
    driver: bridge